apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  claimRef:
    kind: PersistentVolumeClaim
    namespace: mariadb
    name: mariadb
  hostPath:
    path: /mnt/data/mariadb