Vagrant.configure("2") do |config|

  config.vm.box = "rockylinux/9.6"
  # Disk 확장설정 추가
  config.disksize.size = "30GB"

  config.vbguest.auto_update = false
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
  config.vm.provision :shell, privileged: true, inline: $install_default

  config.vm.define "master-node" do |master|
    master.vm.hostname = "k8s-master"
    master.vm.network "private_network", ip: "192.168.56.40"
    master.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--firmware", "efi"]
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
	end
    master.vm.provision :shell, privileged: true, inline: $install_master
    master.vm.provision :shell, privileged: true, inline: $exam_user
  end

end

$install_default = <<-SHELL

echo '======== [4] Rocky Linux 기본 설정 ========'
echo '======== [4-1] 패키지 업데이트 ========'
#yum -y update --releasever=9

echo '======== root 로그인 허용 체크 ========'
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl restart sshd

# 초기 root 비밀번호 변경을 원하시면 아래 주석을 풀고 [새로운비밀번호]에 비번을 입력해주세요
# echo "root:새로운비밀번호" | chpasswd

echo '======== [4-2] 타임존 설정 및 동기화========'
timedatectl set-timezone Asia/Seoul
timedatectl set-ntp true
chronyc makestep

echo '======== [4-3] Disk 확장 ========'
yum install -y cloud-utils-growpart
growpart /dev/sda 5
xfs_growfs /dev/sda5

echo '======= [4-4] hosts 설정 =========='
cat << EOF >> /etc/hosts
192.168.56.30 k8s-master
EOF

echo '======== [5] kubeadm 설치 전 사전작업 ========'
echo '======== [5] 방화벽 해제 ========'
systemctl stop firewalld && systemctl disable firewalld

echo '======== [5] Swap 비활성화 ========'
swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab


echo '======== [6] 컨테이너 런타임 설치 ========'
echo '======== [6-1] 컨테이너 런타임 설치 전 사전작업 ========'
echo '======== [6-1] iptable 세팅 ========'
cat <<EOF |tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

modprobe overlay
modprobe br_netfilter

cat <<EOF |tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

sysctl --system

echo '======== [6-2] 컨테이너 런타임 (containerd 설치) ========'
echo '======== [6-2-1] containerd 패키지 설치 (option2) ========'
echo '======== [6-2-1-1] docker engine 설치 ========'
echo '======== [6-2-1-1] repo 설정 ========'
dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo

echo '======== [6-2-1-1] containerd 설치 ========'
dnf install -y containerd.io-1.7.29-1.el9
systemctl daemon-reload
systemctl enable --now containerd

echo '======== [6-3] 컨테이너 런타임 : cri 활성화 ========'
# defualt cgroupfs에서 systemd로 변경 (kubernetes default는 systemd)
containerd config default > /etc/containerd/config.toml
sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml
systemctl restart containerd

echo '======== [7] kubeadm 설치 ========'
echo '======== [7] repo 설정 ========'
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.34/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.34/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
EOF

echo '======== [7] SELinux 설정 ========'
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

echo '======== [7] kubelet, kubeadm, kubectl 패키지 설치 ========'
yum install -y kubelet-1.34.3-150500.1.1 kubeadm-1.34.3-150500.1.1 kubectl-1.34.3-150500.1.1 --disableexcludes=kubernetes
systemctl enable --now kubelet
SHELL



$install_master = <<-SHELL

echo '======== [8] kubeadm으로 클러스터 생성  ========'
echo '======== [8-1] 클러스터 초기화 (Pod Network 세팅) ========'
kubeadm init --pod-network-cidr=20.96.0.0/12 --apiserver-advertise-address 192.168.56.40

echo '======== [8-2] kubectl 사용 설정 ========'
mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config

echo '======== [8-3] Master 노드에 Pod 생성 허용 ========'
kubectl taint nodes k8s-master node-role.kubernetes.io/control-plane:NoSchedule-

echo '======== [8-4] Pod Network 설치 (calico) ========'
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/install/k8s-cluster-1.34/calico-3.31.1/operator-crds.yaml
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/install/k8s-cluster-1.34/calico-3.31.1/tigera-operator.yaml
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/install/k8s-cluster-1.34/calico-3.31.1/custom-resources.yaml

echo '======== [9] 쿠버네티스 편의기능 설치 ========'
echo '======== [9-1] kubectl 자동완성 기능 ========'
echo "source <(kubectl completion bash)" >> ~/.bashrc
echo 'alias k=kubectl' >>~/.bashrc
echo 'complete -o default -F __start_kubectl k' >>~/.bashrc

echo '======== [9-2] Helm 설치 ========'
curl -O https://get.helm.sh/helm-v3.19.2-linux-amd64.tar.gz
tar -zxvf helm-v3.19.2-linux-amd64.tar.gz
mv linux-amd64/helm /usr/bin/helm

echo '======== [10] 시험 환경을 위한 오픈소스 설치 ========'
echo '======== [10-1] Nginx 설치 ========'
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm pull ingress-nginx/ingress-nginx --version 4.13.4
tar -xf ingress-nginx-4.13.4.tgz
curl -o ./ingress-nginx/values-custom.yaml https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/install/k8s-cluster-1.34/ingress-nginx-1.13.4/helm-4.13.4/values-custom.yaml
helm upgrade --install ingress-nginx ./ingress-nginx -n ingress-nginx --create-namespace -f ./ingress-nginx/values-custom.yaml &

echo '======== [10-2] Gateway API 설치 ========'
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/install/k8s-cluster-1.34/gateway-api-1.4.0/standard-install.yaml

echo '======== [10-3] Cert-Manager 설치 ========'
helm repo add jetstack https://charts.jetstack.io
helm install cert-manager jetstack/cert-manager --version 1.19.1 --namespace cert-manager --create-namespace --set featureGates="ExperimentalCertificateSigningRequestControllers=true" --set installCRDs=true &

SHELL

$exam_user = <<-SHELL

echo '======== [1] CKA 실습용 User 생성 ========'
useradd -m -s /bin/bash cka0001
echo "cka0001 ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/cka0001
chmod 440 /etc/sudoers.d/cka0001
echo "cka0001:cka0001" | chpasswd

echo '======== [1-1] CKA 실습용 kubectl 권한 설정 ========'
mkdir -p /home/cka0001/.kube
cp /etc/kubernetes/admin.conf /home/cka0001/.kube/config
chown -R cka0001:cka0001 /home/cka0001/.kube
chmod 600 /home/cka0001/.kube/config

echo '======== [1-2] CKA 실습용 kubectl 자동 완성 ========'
su - cka0001 -c 'echo "source <(kubectl completion bash)" >> ~/.bashrc'
su - cka0001 -c 'echo "alias k=kubectl" >> ~/.bashrc'
su - cka0001 -c 'echo "complete -o default -F __start_kubectl k" >> ~/.bashrc'

echo '======== [2] 시험 문제를 위한 리소스 설치 ========'
echo '======== [2-1] Storage 환경 세팅 ========'
echo '======== [2-1-1] pvc ========'
mkdir -p /mnt/data/mariadb
chmod 777 /mnt/data/mariadb
kubectl create ns mariadb
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/storage/pvc/storageclass.yaml
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/storage/pvc/pv.yaml
su - cka0001 -c 'mkdir -p ~/pvc-restore'
su - cka0001 -c 'curl -o ~/pvc-restore/mariadb-deploy.yaml https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/storage/pvc/mariadb-deploy.yaml'


echo '======== [2-2] Workloads & Scheduling 환경 세팅 ========'
echo '======== [2-2-hpa] pvc ========'
kubectl create ns autoscale
kubectl create -f https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/workloads-scheduling/hpa/deployment.yaml


echo '======== [2-2-configmap] pvc ========'
kubectl create ns nginx-static
mkdir -p ~/configmap
curl -o ~/configmap/tls.crt https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/workloads-scheduling/configmap/tls.crt
curl -o ~/configmap/tls.key https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/workloads-scheduling/configmap/tls.key
kubectl create secret tls nginx-tls --cert=/root/configmap/tls.crt --key=/root/configmap/tls.key -n nginx-static

curl -o ./configmap/values-nginx.yaml https://raw.githubusercontent.com/k8s-1pro/exam-cka/main/exam/workloads-scheduling/configmap/values-nginx.yaml
helm upgrade --install ingress-config ./ingress-nginx -n nginx-static -f ./configmap/values-nginx.yaml &

SHELL